% set(handles.edit18, 'String',['Коефіцієнт = ' num2str(op), ' ' kko])
% set(handles.edit6, 'String',['Коефіцієнт = ' num2str(dcc), ' ' kkc])
% set(handles.edit6, 'String',['Коефіцієнт = ' num2str(de), ' ' kke])
% set(handles.edit6, 'String',['Коефіцієнт = ' num2str(nkkc), ' ' kkn])
% set(handles.edit6, 'String',['Коефіцієнт = ' num2str(rhnV), ' ' kne])
% set(handles.edit6, 'String',['К =' num2str(dcS),';',num2str(dcH),';',num2str(dcV),'-' kkd])
% set(handles.edit4, 'String',['Коефіцієнт =' num2str(kdtc), ' ' kkt])